#!/usr/bin/env python3
"""Train/evaluate/analyze a DeepLabCut multi-animal project generated by the mouse simulator.

Tailored for the synthetic project layout produced by the renderer:
- multi-animal project with individuals [mouse0, mouse1]
- videos stored under <project>/videos
- labeled-data already generated (CSV/H5 + images)

Typical usage:
    python train_dlc_multi_mouse.py --config /abs/path/to/dlc_synth_project/config.yaml

Then optionally analyze videos after training:
    python train_dlc_multi_mouse.py --config ... --analyze --create-labeled-video --reid
"""
from __future__ import annotations

import argparse
import inspect
import os
import sys
from pathlib import Path
from typing import List, Optional

import yaml


def _load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _default_videos_dir_from_config(cfg: dict) -> Optional[str]:
    project_path = cfg.get("project_path")
    if not project_path:
        return None
    return str(Path(project_path) / "videos")


def _list_videos(videos_dir: str, videotype: str) -> List[str]:
    p = Path(videos_dir)
    if not p.exists():
        return []
    ext = videotype if videotype.startswith(".") else f".{videotype}"
    return sorted(str(x) for x in p.glob(f"*{ext}"))




def _kw_if_supported(fn, **kwargs):
    """Return kwargs filtered to parameters supported by fn (for DLC version compatibility)."""
    try:
        sig = inspect.signature(fn)
        params = sig.parameters
    except Exception:
        return kwargs
    return {k: v for k, v in kwargs.items() if k in params and v is not None}

def main() -> None:
    ap = argparse.ArgumentParser(description="Train/evaluate/analyze a multi-animal DLC project (2 mice).")
    ap.add_argument("--config", default="dlc_synth_project/config.yaml", help="Path to DLC config.yaml")
    ap.add_argument("--shuffle", type=int, default=1, help="DLC shuffle index")
    ap.add_argument("--trainingsetindex", type=int, default=0, help="Training fraction index (usually 0)")
    ap.add_argument("--gputouse", type=int, default=None, help="Optional GPU index for DLC")
    ap.add_argument("--maxiters", type=int, default=None, help="Optional max iterations for train_network")
    ap.add_argument("--displayiters", type=int, default=1000)
    ap.add_argument("--saveiters", type=int, default=50000)
    ap.add_argument("--videotype", default="mp4")
    ap.add_argument("--engine", default="pytorch", choices=["pytorch", "tensorflow", "auto"],
                    help="DLC engine to request where supported (default: pytorch)")

    # Stages (all enabled by default except analysis/video export)
    ap.add_argument("--skip-check-labels", action="store_true", help="Skip dlc.check_labels")
    ap.add_argument("--skip-create-dataset", action="store_true", help="Skip dlc.create_training_dataset")
    ap.add_argument("--skip-train", action="store_true", help="Skip dlc.train_network")
    ap.add_argument("--skip-eval", action="store_true", help="Skip dlc.evaluate_network")

    ap.add_argument("--analyze", action="store_true", help="Analyze videos after training/eval")
    ap.add_argument("--videos-dir", default=None, help="Directory of videos to analyze (default: <project>/videos)")
    ap.add_argument("--create-labeled-video", action="store_true", help="Create labeled output videos after analyze")
    ap.add_argument("--plot-trajectories", action="store_true", help="Plot trajectories after analyze")

    # Multi-animal identity refinement (optional; DLC version dependent)
    ap.add_argument("--reid", action="store_true", help="Run transformer_reID after analyze (if available)")
    ap.add_argument("--n-tracks", type=int, default=2, help="Number of tracked animals (2 mice)")

    args = ap.parse_args()

    cfg_path = os.path.abspath(args.config)
    if not os.path.exists(cfg_path):
        raise FileNotFoundError(cfg_path)

    cfg = _load_config(cfg_path)
    if not bool(cfg.get("multianimalproject", False)):
        print("WARNING: config does not declare multianimalproject=true", file=sys.stderr)

    try:
        import deeplabcut as dlc
    except Exception as e:
        raise RuntimeError(
            "Could not import deeplabcut. Activate your DLC environment first, e.g. 'conda activate dlc_mouse'."
        ) from e

    print(f"Using DLC config: {cfg_path}")
    print(f"Requested engine: {args.engine}")
    print(f"Multi-animal: {cfg.get('multianimalproject')} | individuals={cfg.get('individuals')} | bodyparts={cfg.get('multianimalbodyparts')}")

    common_kwargs = {}
    if args.gputouse is not None:
        common_kwargs["gputouse"] = args.gputouse

    engine_kwargs = {}
    if args.engine != "auto":
        engine_kwargs["engine"] = args.engine

    if not args.skip_check_labels:
        print("[1/4] Checking labels...")
        # visualizeindividuals helps for multi-animal projects
        dlc.check_labels(cfg_path, visualizeindividuals=True)

    if not args.skip_create_dataset:
        print("[2/4] Creating training dataset...")
        create_kwargs = dict(
            Shuffles=[args.shuffle],
            trainingsetindex=args.trainingsetindex,
        )
        create_kwargs.update(engine_kwargs)
        dlc.create_training_dataset(cfg_path, **_kw_if_supported(dlc.create_training_dataset, **create_kwargs))

    if not args.skip_train:
        print("[3/4] Training network...")
        train_kwargs = dict(
            shuffle=args.shuffle,
            trainingsetindex=args.trainingsetindex,
            displayiters=args.displayiters,
            saveiters=args.saveiters,
        )
        train_kwargs.update(common_kwargs)
        train_kwargs.update(engine_kwargs)
        if args.maxiters is not None:
            train_kwargs["maxiters"] = args.maxiters
        dlc.train_network(cfg_path, **_kw_if_supported(dlc.train_network, **train_kwargs))

    if not args.skip_eval:
        print("[4/4] Evaluating network...")
        eval_kwargs = dict(Shuffles=[args.shuffle], trainingsetindex=args.trainingsetindex)
        eval_kwargs.update(common_kwargs)
        eval_kwargs.update(engine_kwargs)
        dlc.evaluate_network(cfg_path, **_kw_if_supported(dlc.evaluate_network, **eval_kwargs))

    if args.analyze:
        videos_dir = args.videos_dir or _default_videos_dir_from_config(cfg)
        if not videos_dir:
            raise ValueError("Could not infer videos directory from config; pass --videos-dir")
        video_list = _list_videos(videos_dir, args.videotype)
        if not video_list:
            raise FileNotFoundError(f"No *.{args.videotype.lstrip('.')} files found in {videos_dir}")

        print(f"Analyzing {len(video_list)} video(s) from {videos_dir} ...")
        analyze_kwargs = dict(videotype=args.videotype)
        analyze_kwargs.update(common_kwargs)
        analyze_kwargs.update(engine_kwargs)
        dlc.analyze_videos(cfg_path, [videos_dir], **_kw_if_supported(dlc.analyze_videos, **analyze_kwargs))

        if args.reid:
            reid_fn = getattr(dlc, "transformer_reID", None)
            if reid_fn is None:
                print("[reID] transformer_reID not available in this DLC version; skipping.")
            else:
                print("Running transformer_reID (n_tracks=2)...")
                reid_fn(cfg_path, [videos_dir], n_tracks=args.n_tracks, videotype=args.videotype)

        if args.create_labeled_video:
            print("Creating labeled videos...")
            clv_kwargs = dict(videotype=args.videotype)
            clv_kwargs.update(engine_kwargs)
            dlc.create_labeled_video(cfg_path, [videos_dir], **_kw_if_supported(dlc.create_labeled_video, **clv_kwargs))

        if args.plot_trajectories:
            print("Plotting trajectories...")
            pt_kwargs = dict(videotype=args.videotype)
            pt_kwargs.update(engine_kwargs)
            dlc.plot_trajectories(cfg_path, [videos_dir], **_kw_if_supported(dlc.plot_trajectories, **pt_kwargs))

    print("Done.")


if __name__ == "__main__":
    main()
